{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:8: AssertionError"}, "start": 1665047335803, "stop": 1665047335804, "uuid": "e26bf606-f668-456f-ac87-d3eea3522c79", "historyId": "939d0d34fdd0a77844bacb76dac07bab", "testCaseId": "3871665697ea3d8351c8bbb21a2393bd", "fullName": "tests.simple.test_fail#test_fail3", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "DESKTOP-CC7BMFU"}, {"name": "thread", "value": "3704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}