{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:8: AssertionError"}, "start": 1665059299712, "stop": 1665059299713, "uuid": "480e10f5-c592-4d93-a13b-daf9787f8733", "historyId": "939d0d34fdd0a77844bacb76dac07bab", "testCaseId": "3871665697ea3d8351c8bbb21a2393bd", "fullName": "tests.simple.test_fail#test_fail3", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "DESKTOP-CC7BMFU"}, {"name": "thread", "value": "3760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}