{"name": "test_fail5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail5():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:14: AssertionError"}, "start": 1665047335818, "stop": 1665047335819, "uuid": "9a87e1f5-48f1-472f-8f0f-66ee5a30fb72", "historyId": "0fef2d7cf3da80e165e4bf69df443b68", "testCaseId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "fullName": "tests.simple.test_fail#test_fail5", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "DESKTOP-CC7BMFU"}, {"name": "thread", "value": "3704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}