{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:6: AssertionError"}, "start": 1665047335795, "stop": 1665047335795, "uuid": "0ffce395-b953-4ba5-8d39-184810d5dc8d", "historyId": "21ab75b857ff76ad1422635d4e7b4e76", "testCaseId": "c34ce9c1ddd89c5349df16e9084d0f7d", "fullName": "tests.simple.test_fail#test_fail2", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "DESKTOP-CC7BMFU"}, {"name": "thread", "value": "3704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}