{"name": "test_fail1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail1():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:2: AssertionError"}, "start": 1665059299696, "stop": 1665059299696, "uuid": "cd46e17e-e002-49cd-b4c7-5c7de47ff3a7", "historyId": "dc0ceebed11c4ccce398ae2314fa1cd9", "testCaseId": "5980a0f138d2262d80936b48f834090e", "fullName": "tests.simple.test_fail#test_fail1", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "DESKTOP-CC7BMFU"}, {"name": "thread", "value": "3760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}